#!/usr/bin/env ruby
require 'erb'
require 'pathname'

app = ARGV[0]
root = ENV['DOKKU_ROOT']
domainspath = File.join(root, app, 'DOMAINS')
vhostpath = File.join(root, 'VHOST')
forcesslpath = File.join(root, app, 'FORCE_SSL')

exit unless File.exists?(domainspath)

force_ssl = File.exists?(forcesslpath)
vhost = File.read(vhostpath).strip
hostname = "#{app.sub('/','-')}.#{vhost} " + File.read(domainspath).strip
port = File.read(File.join(root, app, 'PORT')).strip

ssl_dirs = [File.join(root, app, 'ssl'), File.join(root, app, 'tls'), File.join(root, 'ssl'), File.join(root, 'tls')]
use_ssl = false
ssl = ''

ssl_dirs.each { |dir|
  if File.exists?(File.join(dir, 'server.crt')) && File.exists?(File.join(dir, 'server.key'))
    use_ssl = true
    ssl = dir
  end
}

# write app/nginx.conf
template = File.open(File.join(Pathname.new(__FILE__).dirname, 'nginx.conf.erb'), 'rb').read
File.open(File.join(root, app, 'nginx.conf'), 'w') { |file| file.write(ERB.new(template).result) }

# write app/URL
url = "#{use_ssl ? 'https' : 'http'}://#{hostname.split(" ")[0]}"
File.open(File.join(root, app, 'URL'), 'w') { |file| file.write(url) }
